name: Skyblock
version: 0.0.1
main: com.shreyaslad.skyblock.Skyblock
api-version: 1.13
authors: [3YD]
description: A simple Skyblock plugin
commands:
  skyblock:
    description: Displays the skyblock help section
